version: '3.2'
services:
  tgdb_website:
    image: webdevops/php-apache-dev:8.2
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/website
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=128M
      - PHP_MAX_EXECUTION_TIME=5
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_MAX_NESTING_LEVEL=1000
    networks:
      - internal
    ports:
      - "8080:80"
    volumes:
      - ./:/app:rw,cached

  tgdb_api:
    image: webdevops/php-apache-dev:8.2
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/API
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=128M
      - PHP_MAX_EXECUTION_TIME=5
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_MAX_NESTING_LEVEL=1000
    networks:
      - internal
    ports:
      - "8088:80"
    volumes:
      - ./:/app:rw,cached
      - ./docker/apache/:/opt/docker/etc/httpd/vhost.common.d:ro

  mariadb:
    image: mariadb:10.5
    networks:
      - internal
    environment:
      - MARIADB_ROOT_PASSWORD=abc123
      - MARIADB_DATABASE=TGDB
    ports:
      - "13306:3306"
    volumes:
      - docker-data:/var/lib/mysql
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  internal:

volumes:
  docker-data:
